_welcome:
    pattern:  /
    defaults: { _controller: BBCBundle:Demo:index }

_services:
    pattern:  /services
    defaults: { _controller: BBCBundle:Demo:services }

_schedule:
    pattern:  /schedule/{service}
    defaults: { _controller: BBCBundle:Demo:schedule }

_episode:
    pattern:  /episode/{pid}
    defaults: { _controller: BBCBundle:Demo:episode }
